-- nlog_user用户表【id、password(密码)、last_login(上次一登录时间)、is_superuser(是否管理员)、username(用户名)、firstname(姓)、lastname(名)、email(邮箱)、is_staff()、is_active()、date_joined(创建时间)、avatar(头像)、qq(QQ号码)、mobile(手机号码)、url(个人博客地址)】
-- blog_tag标签表【id、tag(标签名)】
-- blog_category分类表【id、name(分类名称)、index(分类排序)】
-- blog_article文章表【id、title(文章标题)、desc(文章描述)、content(文章内容)、ckick_count(点击次数)、is_recommend(是否推荐)、date_publish(发布时间)、user(用户)、category(分类)、tag(标签)】
-- blog_comment评论表【id、content(评论内容)、username(用户名)、email(邮箱地址)、url(个人网页地址)、date_publish(发布时间)、user(用户)、article(文章)、pid(父级评论)】
-- blog_links友情链接【id、title(标题)、description(友情链接描述)、callback_url(url地址)、date_publish(发布时间)、index(排列顺序)】
-- blog_ad广告【id、title(广告标题)、description(广告描述)、image_url(图片路径)、callback_url(回调url)、date_publish(发布时间)、index(排列顺序)】